"""
Django settings for test_koalixcrm project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""
from .base_settings import *

# Update database configuration with $DATABASE_URL.
import dj_database_url
DATABASES = { 'default': dj_database_url.config(conn_max_age=500,default='postgres://plqvypjsypejcc:2d4a407cf85fa825ba18a655651dd24f34b02d96c489479df3598502c547d81a@ec2-46-137-156-205.eu-west-1.compute.amazonaws.com:5432/d3vl1t8f2jf16j') }
FOP_EXECUTABLE = "/usr/bin/fop"
GRAPPELLI_INDEX_DASHBOARD = 'projectsettings.dashboard.CustomIndexDashboard'
ALLOWED_HOSTS = ['koalix-crm.herokuapp.com']

KOALIXCRM_REST_API_AUTH = True
